### ISSUE TITLE
servers page does not load on librewolf

### ISSUE THREAD

**Issue by peepee** [leighmacdonald/uncledane-web#45]
judging by the console output, the issue seems to be related to the map that shows on the page. maybe the page refuses to finish loading if the map doesn't load? i suspect this is also a problem on other privacy-centric browsers like ungoogled-chromium and the tor browser bundle.

![librewolfuncledane](https://user-images.githubusercontent.com/49787675/132138980-2839e4ef-11a1-40b2-93e6-701d83530e39.png)

**Comment by leighmacdonald** [comment]
Should be resolved now.
