### ISSUE TITLE
HUDS.TF links no longer working

### ISSUE THREAD

**Issue by rbjaxter** [leighmacdonald/uncledane-web#60]
Hey there!

HUDS.TF shut down (at least the website) on 1/30. On the settings page (https://uncledane.com/settings), the budhud and rayshud links no longer work.

There is now an alternative, hosted by mastercoms (https://comfig.app/huds/1/). The two huds can be found on there below:
- budhud: https://comfig.app/huds/page/budhud/
- rayshud: https://comfig.app/huds/page/rayshud/

Alternatively, you could also link to the GitHub sites:
- budhud: https://github.com/rbjaxter/budhud
- rayshud: https://github.com/raysfire/rayshud

**Comment by leighmacdonald** [comment]
@rbjaxter Thanks, these have been updated :+1:
