### ISSUE TITLE
"www" subdomain gets a 525 SSL handshake error

### ISSUE THREAD

**Issue by gunr2171** [leighmacdonald/uncledane-web#9]
I know, this has nothing to do with the code in this repository. I'm sorry. It's the best place I could think of to report this issue.

Dane's YouTube profile page links to the website:
![image](https://user-images.githubusercontent.com/8290105/103163215-3d74de80-47c9-11eb-8ab2-ec46741d72c7.png)

Problem is the url is "https://www.uncledane.com/", with the "www" subdomain. And that is broken:

![image](https://user-images.githubusercontent.com/8290105/103163247-afe5be80-47c9-11eb-9088-b5c01a92d4f7.png)

Which is odd because it looks like the cert has the correct subdomain wildcard:

![image](https://user-images.githubusercontent.com/8290105/103163265-ec191f00-47c9-11eb-9cc4-95a798920acc.png)

IDK, Cloudflare must not like it.

**Comment by leighmacdonald** [comment]
Thanks for the report, will take a look.

**Comment by UncleDane** [comment]
Fixed this on my end, thanks
